Repository faasm/faasm, pull requests merged in 2020-11, with the labels that each got.

#332 Container tooling
  bin/cli.sh
  bin/stop-cli.sh
  bin/workon.sh
  docker/docker-compose-cli.yml
  docs/development.md
Labels: enhancement

#349 Adding stubbed syscalls for popen and pclose
  src/wavm/process.cpp
Labels: enhancement

#354 Specific test tag for MPI Tests
  tests/test/faaslet/test_mpi.cpp
Labels: ci

#345 Add SGX SDK to containers
  .env
  .github/workflows/tests.yml
  CMakeLists.txt
  VERSION
  cmake/FindSGX.cmake
  deploy/k8s/bare-metal/upload-pod.yml
  deploy/k8s/common/redis-queue.yml
  deploy/k8s/common/redis-state.yml
  docker/base.dockerfile
  docker/sgx.dockerfile
  docs/sgx.md
  faasmcli/faasmcli/tasks/compile.py
  faasmcli/faasmcli/util/compile.py
  include/sgx/SGXWAMRWasmModule.h
  include/sgx/faasm_sgx_system.h
  include/sgx/faasm_sgx_whitelisting.h
  include/wamr/WAMRWasmModule.h
  src/faaslet/CMakeLists.txt
  src/sgx/faasm_sgx_enclave.cpp
  src/sgx/faasm_sgx_enclave.edl
  src/sgx/faasm_sgx_native_symbols_wrapper.cpp
  src/sgx/sgx_wamr_enclave.cpp
  src/storage/CMakeLists.txt
  src/storage/FileLoader.cpp
  src/wamr/CMakeLists.txt
  tests/test/faaslet/test_python.cpp
  tests/test/wasm/test_cloning.cpp
Labels: sgx

#358 SGX tests in CI
  docs/sgx.md
  faasmcli/faasmcli/tasks/codegen.py
  include/faaslet/FaasletPool.h
  src/sgx/CMakeLists.txt
  src/sgx/faasm_sgx_system.cpp
  src/storage/FileLoader.cpp
  tests/test/sgx/test_sgx.cpp
  tests/test/wamr/test_wamr.cpp
  tests/utils/utils.h
  tests/utils/worker_utils.cpp
Labels: sgx

#359 Fix directory listing bug
  .github/workflows/tests.yml
  bin/print_cpu.sh
  docker/docker-compose-ci.yml
  func/python/dir_test.py
  func/python/lang_test.py
  include/faaslet/FaasletPool.h
  include/storage/FileDescriptor.h
  src/storage/FileDescriptor.cpp
  src/wavm/io.cpp
  tests/test/faaslet/test_python.cpp
  tests/test/module_cache/test_module_cache.cpp
  tests/test/storage/test_file_descriptor.cpp
  tests/test/wasm/test_cloning.cpp
  tests/utils/utils.h
  tests/utils/worker_utils.cpp
Labels: maintenance

#326 Pass over MPI Tests
  func/mpi/mpi_checks.cpp
  func/mpi/mpi_isendrecv.cpp
  func/mpi/mpi_onesided.cpp
  func/mpi/mpi_probe.cpp
  func/mpi/mpi_put.cpp
  func/mpi/mpi_reduce_dbl.cpp
  func/mpi/mpi_status.cpp
  func/mpi/mpi_wincreate.cpp
  src/wavm/mpi.cpp
Labels: maintenance

#364 Parallelise Docker build
  .github/workflows/release.yml
Labels: docker

#362 Remove python experiment code
  func/python/bench_chaos.py
  func/python/bench_deltablue.py
  func/python/bench_dulwich.py
  func/python/bench_fannkuch.py
  func/python/bench_float.py
  func/python/bench_genshi.py
  func/python/bench_go.py
  func/python/bench_hexiom.py
  func/python/bench_json_dumps.py
  func/python/bench_json_loads.py
  func/python/bench_logging.py
  func/python/bench_mdp.py
  func/python/bench_nbody.py
  func/python/bench_pickle.py
  func/python/bench_pidigits.py
  func/python/bench_pyaes.py
  func/python/bench_pyflate.py
  func/python/bench_raytrace.py
  func/python/bench_richards.py
  func/python/bench_scimark.py
  func/python/bench_spectral_norm.py
  func/python/bench_telco.py
  func/python/bench_unpack_sequence.py
  func/python/bench_version.py
Labels: maintenance

#366 CMake Versioning Hot-Fix
  cmake/ExternalProjects.cmake
  libs/faasmpi/CMakeLists.txt
Labels: ci

#368 MPI_Scan implementation in the faasm side
  func/mpi/CMakeLists.txt
  func/mpi/mpi_scan.cpp
  src/wavm/mpi.cpp
  tests/test/faaslet/test_mpi.cpp
Labels: faabric

#333 Incorporate Clang Tidy
  .clang-tidy
  .env
  .github/workflows/tests.yml
  README.md
  VERSION
  bin/run_clang_tidy.sh
  deploy/k8s/bare-metal/upload-pod.yml
  deploy/k8s/common/redis-queue.yml
  deploy/k8s/common/redis-state.yml
  docker/cli.dockerfile
  func/mpi/mpi_typesize.cpp
  func/omp/intel_nstreams.cpp
  func/omp/intel_synch_p2p.cpp
  func/omp/intel_transpose.cpp
  func/omp/reduction_integral.cpp
  src/sgx/faasm_sgx_enclave.cpp
  src/sgx/rw_lock.cpp
Labels: ci, maintenance
